### ISSUE TITLE
Container_definition question.

### ISSUE THREAD

**Issue by ShitulGupta** [mongodb/terraform-aws-ecs-task-definition#29]
In the below code snippet what is the difference between [%s] and %s with the terraform format function.

container_definition = var.register_task_definition ? format("[%s]", data.template_file.container_definition.rendered) : format("%s", data.template_file.container_definition.rendered)

Would really appreciate a quick response on this.

**Comment by jasonwalsh** [comment]
Hi @ShitulGupta 👋 

The `container_definitions` directive of the [`aws_ecs_task_definition`](https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html) must be an array of [container definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definitions) objects.

For example, the following code:

```hcl
module "mongo-task-definition" {
  source = "github.com/mongodb/terraform-aws-ecs-task-definition"

  family = "mongo"
  image  = "mongo:3.6"
  memory = 512
  name   = "mongo"

  portMappings = [
    {
      containerPort = 27017
    },
  ]

  register_task_definition = false
}
```

generates the following JSON document:


```json
{
  "command": null,
  "cpu": null,
  "disableNetworking": false,
  "dnsSearchDomains": null,
  "dnsServers": null,
  "dockerLabels": null,
  "dockerSecurityOptions": null,
  "entryPoint": null,
  "environment": null,
  "essential": true,
  "extraHosts": null,
  "healthCheck": null,
  "hostname": null,
  "image": "mongo:3.6",
  "interactive": false,
  "links": null,
  "linuxParameters": null,
  "logConfiguration": null,
  "memory": 512,
  "memoryReservation": null,
  "mountPoints": null,
  "name": "mongo",
  "portMappings": [
    {
      "containerPort": 27017
    }
  ],
  "privileged": false,
  "pseudoTerminal": false,
  "readonlyRootFilesystem": false,
  "repositoryCredentials": null,
  "resourceRequirements": null,
  "secrets": null,
  "systemControls": null,
  "ulimits": null,
  "user": null,
  "volumesFrom": null,
  "workingDirectory": null
}
```

However, the preceding JSON document is *not* valid, since it is a single object and not an array of container definition objects.

If you set `register_task_definition = true`, then it will pre/post-fix `[` and `]` tokens, respectively to the serialized string, thus making the input of the `container_definitions` directive valid.

The reason I designed the module like this is because often times people require more than just one container definition in their task definition.

When you have a moment, please refer to the README of the [`merge`](https://github.com/mongodb/terraform-aws-ecs-task-definition/tree/master/modules/merge) submodule as it explains how you can combine the outputs of this module to create a task definition with more than one container definition.

Let me know if that helps.

**Comment by ShitulGupta** [comment]
Thanks @jasonwalsh , really appreciate your quick response on this. The explanation here really helps.

**Comment by jasonwalsh** [comment]
Closing this issue. Please create another issue if you have any further questions.
